version: "3"
services:
  pyglidein-server:
    image: wipac/pyglidein_server:1.0
    networks:
      app_net:
    hostname: pyglidein-server
  pyglidein-client:
    image: wipac/pyglidein_client:1.0
    networks:
      app_net:
    hostname: pyglidein-client
    privileged: true
  minio:
    image: minio/minio
    networks:
      app_net:
    hostname: minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data



networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 172.22.0.0/24
