version: "3"
services:
  pyglidein-server:
    image: wipac/pyglidein_server:1.0
    networks:
      app_net:
    hostname: pyglidein-server
    volumes:
      - "../:/pyglidein"
      - "~/.pyglidein_secrets_server:/home/condor/.pyglidein_secrets"
  pyglidein-client:
    image: wipac/pyglidein_client_centos${OS_VERSION:-7}:1.0
    networks:
      app_net:
    hostname: pyglidein-client
    privileged: true
    volumes:
      - "../:/pyglidein"
      - "~/.pyglidein_secrets:/home/pyglidein/.pyglidein_secrets"
  minio:
    image: minio/minio
    networks:
      app_net:
    hostname: minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 172.22.0.0/24
